const princess = [
  "## Act 1\n_Frogman leans on the wall of a grungy basement. An old mop is propped up next to a rusty washbucket. Frogman whistles while he lights a cigarette._",
  "#### Frogman\n9pm, about quitting time down here. My old life, it never changes. But I like it this way. I like it a lot. I'm the castle's artist. Scrubbing floors, doing dishes, and my favorite part: flushing the toilets. That's why I save the best for last. Cleaning the private throne of princess pops. No I'm not a creep. I'm a janitor. I'm motivated. Now let's get to work so I can get home to my sweet dreams.",
  "#### Princess Pops\n_(On the toilet, in a moment of deep reflection)_\nThe kingdom is changing. 1000 years I've been a princess. I've seen us through hard times. I fought off beasts and bandits by my own hand, and now we have the longest period of peace in history. I can rest. Bust my father wants me to marry? Find the next King? No way. I have my life to live. Memoirs to write. And it begins now. *FLUSH*",
  "#### Frogman\nAbout done?",
  "#### Princess Pops\nExcuse me!",
  "#### Frogman\n_(lights a cigarette)_\nExcuse me too. Sorry, take your time. I'm wrapping up around here.",
  "#### Princess Pops\nHow about a little space?",
  "#### Frogman\nI was just gonna say it smells great in here. You're a healthy woman.",
  "#### Princess Pops\nI eat a lot of pie. But that's not for you to smell or comment on.",
  "#### Frogman\nSuit yourself. I'll swing back in a few minutes.",
  "#### Princess Pops\nThere's no smoking in here.",
  "#### Frogman\n_(takes a deep drag, then puts out his cigarette)_\nI know.",
  "#### Princess Pops\nWait!",
  "#### Frogman\nYeah?",
  "#### Princess Pops\nHow long have you worked here?",
  "#### Frogman\nPops, I cleaned up after your grandma and your grandma's grandma. Only thing that's changed is flavor of the pies.",
  "#### Princess Pops\n_(laughs)_\nGreat joke. How have we never met?",
  "#### Frogman\nOh we've met. You may have been battling chimmies while I mopped blood off the front gate. In those years you were pretty pre-occupied.",
  "#### Princess Pops\nSo, thousands of years in the castle, and you never picked up bathroom etiquette?",
  "#### Frogman\nI'm a rebel baby. But okay. Here, you've got some pop on your dress. I've got something that'll help.",
  "#### Princess Pops\nOh no! No... it's ruined.",
  "#### Frogman\nLike I said Pops, your grandma's grandma—I've seen it all. Here's a little green serum from a far away land. Neutralizes the pop.",
  "#### Princess Pops\nAll right already! Hands off. But, thank you. I have to go. My father is shopping me around to a local prince.",
  "#### Frogman\nPrince Juicifer I hear. Lucky you.",
  "#### Princess Pops\nActually I'm sick to my stomach, thinking of his fat fingers digging through his food while he stares at me and licks his lips. My last suitor kept wiping his greasy fingers on his lap, rubbing the erection under his napkin like I didn't notice, then plunging his hands back into the fondue for an excuse to rub it on himself. Meanwhile, I sat and smiled at his parents. I'm a thousand years old, and they treat me like a doll. But do you know what I do to these men, after our dads leave us to flirt by ourselves? After I've sat there an hour, smiling, without touching my food?",
  "#### Frogman\nMake fun of their eating habits some more?",
  "#### Princess Pops\n_(licks her lips)_\nI eat them of course.",
  "## Act 2\n_6:00am. Frogman is in the kitchen slicing some breads._",
  "#### Frogman\nIs this... a complaint?\n\n_To the castle staff,\nI've never had a more horrendous meal in my life. I wouldn't call it curry, and I wouldn't call it casserole. It was a soupy abomination that I already feel gurgling its way back up. I demand you fire the kitchen staff at once if my son is ever to marry into this family. He is alone with Priness Pop now, but he'll be hearing about this from me.\nYours,\nKing Juicifer_\n\nOh no. Another complaint about my casserole. What am I going to do. It was my last warning. Crap.",
  "#### Princess Pops\nYou found that jerkwad's letter?",
  "#### Frogman\nShiggity Princess, yeah. I gotta start looking for a new job.",
  "#### Princess Pops\nI got you Frogman. No one's going to see that letter, or hear from King Juicifer again.",
  "#### Frogman\nNice. How'd he taste?",
  "#### Princess Pops\nIt was purely a favor to you. Today I'm very bloated as a result.",
  "#### Frogman\nSomething tells me I shouldn't be hanging around with you.",
  "#### Princess Pops\nWell, now you kept your job. You're stuck with me.",
  "#### Frogman\nSo, you're not interested in impressing these princes, huh?",
  "#### Princess Pops\nMarriage is a celebration of codependency, especially royal marriages. My mom's biggest regret was marrying my dad. Sure she became queen, fulfilled her destiny, all that. But she constantly has to follow his expectations. Me, no. You can catch me on the battlefield, sharing a beer with friends, or belting out on stage in my band. But I won't be caught dead in a man's bed pretending I'm cold and need a warm sweaty ass to feel safe.",
  "#### Frogman\nOh, man, I love a sweaty ass.",
  "#### Princess Pops\nA big hairy one?",
  "#### Frogman\nWith acne, yeah.",
  "#### Princess Pops\nWhat about you Frogman?",
  "#### Frogman\nNever was married, never thought about it. I'm a working guy. Not much family, you know?",
  "#### Princess Pops\nWhat about back in the sewer?",
  "#### Frogman\nSigh, yeah. It seems like so long ago. I have friends back there. Not sure we'd get along today. They're doing band stuff, hanging around the same dives, eating poop. I'm over it, I'm here. So yeah, I'm basically on my own up here. I'm figuring things out.",
  "#### Princess Pops\nCool. A loner. That's sexy.",
  "#### Frogman\nI know.",
  "#### Princess Pops\n_(Licks her lips)_\nOh Frogman.",
  "#### Frogman\nYou gonna eat me?\n_(kisses Pops)_",
  "## Act 3\n_3 years later. Princess Pops puts her jewels on, getting ready for a royal banquet. She is impatient and having a fit._",
  "#### Frogman\nPops! Check this on out!",
  "#### Princess Pops\nSigh, Frog, I'm busy.",
  "#### Frogman\nDude I'm marching all around your bedroom. I'm like a 1980's Russian guy!",
  "#### Princess Pops\nWe have to go. Get ready!",
  "#### Frogman\nI'm ready",
  "#### Princess Pops\nI can't believe you're wearing a tshirt. I thought you wanted to be a part of my family.",
  "#### Frogman\nI'm not comfortable in royal suits.",
  "#### Princess Pops\nBecause you've never worn one!",
  "#### Frogman\nToday isn't even a big deal. I'll wear one when I need to.",
  "#### Princess Pops\nRight, and you'll look completely uncomfortable.",
  "#### Frogman\nYou're telling me I don't know how to wear a suit?",
  "#### Princess Pops\nThat's not what I said. It just looks better...",
  "#### Frogman\n...Better on someone more royal? Someone born in a castle?",
  "#### Princess Pops\nStop! You're the one being difficult. I'm just asking you to care.",
  "#### Frogman\nYou're asking me to be someone I'm not. You're always holding out for me tob e someone different.",
  "#### Princess Pops\nIt's called compromise. Try it out.",
  "#### Frogman\nI compromise! Jesus!\n_(turns away)_",
  "#### Princess Pops\nI don't know what to say.",
  "#### Frogman\nJust go do your thing. I don't belong there.",
  "#### Princess Pops\nLook at me. God dammit, look at me!",
  "#### Frogman\nSorry I'm not perfect. Leave me alone.",
  "#### Princess Pops\n_(to self)\nI can't stand to see him like this. What did I do? Ask him for a favor. I bend and break for him every day. I show him love, and it's easy, most of the time. Is it this hard for other people? Do other people have to march around the castle just to appease their boyfriends? Or does Frogman just not love me enough?\n(to Frogman)_\nDo you not love me?",
  "#### Frogman\nI love you. But I'm not a prince...",
  "#### Princess Pops\nI don't want you to be. I just want to be with you.",
  "#### Frogman\nThat's all you want?",
  "#### Princess Pops\nYes...",
  "#### Frogman\nI'm such an idiot.",
  "#### Princess Pops\nI don't care what the kingdom thinks of you. What my dad says. We'll go away together if we have to.",
  "#### Frogman\n Pops, this isn't about the castle. I'm sorry.. I spent an hour on the phone with your parents yesterday, and I'll tell you what I told them. In 37 months, what's happened? We moved across the country, got rashes on our butts, wrote hundreds of angry journal pages, went through three road trips, and 43 coffee shops. You warm my heart in the weirdest places: crying on a therapist's couch, drinking wine in the cemetery, kissing in a steamy botanical garden, and laughing in the closet. I can't believe it took 30 years to find someone, despite all our jup. I guess I'm the kind of frog who has a panic attack when I think about marriage. You remember when you wanted to break up while I was in Mexico? We're kinda picky or cynical. We're definitely haters. But I'm glad it wasn't easy, because I only want to love you. You're ma petite chou, ma poule, my sweet bean, and a cute little ant. You're so much to me, you feel so right, that it's obvious we can stay together, and be so happy, and I want to. So, that's my proposal—that we stay together forever. We live in the sewer, through panic attacks, caffeine withdrawal, and sobbing therapy sessions... Will you marry me?",
  "## Epilogue\n_10 years later. The sun is low, out at sea, casting orange shadows on the windswept beach. Princess Pops marches in place. Frogman marches too._",
  "#### Princess Pops\nBouncin around!",
  "#### Frogman\nBoun-bouncin around, bouncin!",
  "#### Princess Pops\nMmm, I love you Frog.",
]
