const princess = [
  "## Act 1\n_Frogman leans on the wall of a grungy castle basement. An old mop is propped up next to a  washbucket. Frogman whistles and lights a cigarette._",
  "#### Frogman\n9pm, about quitting time down here. This old life, it never changes. But I like it this way. I like it a lot. I'm the castle's artist. I make the floors sparkle, the meals delicious, and my favorite part: I flush the toilets. That's why I save the best for last. Cleaning the private throne of Princess Pops. No I'm not a creep. Just a janitor. I'm a professional. Now let's get to work so I can get home to my sweet dreams.",
  "#### Princess Pops\n_(On the toilet, in a moment of deep reflection)_\nThe kingdom is changing. 1000 years I've been a princess. I've seen us through hard times. I fought off beasts and bandits by my own hand, and now we have the longest period of peace in history. I can rest. But my father wants me to marry? Find the next King? No way. I have my life to live. Memoirs to write. And it begins now. *FLUSH*",
  "#### Frogman\nYou about done?",
  "#### Princess Pops\nExcuse me!",
  "#### Frogman\n_(lights a cigarette)_\nExcuse me too. Sorry, take your time. I'm wrapping up around here.",
  "#### Princess Pops\nHow about a little space?",
  "#### Frogman\nI was just gonna say it smells great in here. You're a healthy woman.",
  "#### Princess Pops\nI eat a lot of pie. But that's not for you to smell or comment on.",
  "#### Frogman\nSuit yourself. I'll swing back in a few minutes.",
  "#### Princess Pops\nThere's no smoking in here.",
  "#### Frogman\n_(takes a deep drag, then puts out his cigarette)_\nI know.",
  "#### Princess Pops\nWait!",
  "#### Frogman\nYeah?",
  "#### Princess Pops\nHow long have you worked here?",
  "#### Frogman\nPops, I cleaned up after your grandma and your grandma's grandma. Only thing that's changed is the flavor of the pies.",
  "#### Princess Pops\n_(laughs)_\nGreat joke. How have we never met?",
  "#### Frogman\nOh we've met. You were battling chimmies while I mopped blood off the front gate. In those years you were pretty pre-occupied.",
  "#### Princess Pops\nSo, thousands of years in the castle, and you never picked up bathroom etiquette?",
  "#### Frogman\nI'm a rebel baby. But okay, you want some privacy, you got it. Here, you've got some pop on your dress. Let me help you.",
  "#### Princess Pops\nOh what! Noooo... it's ruined.",
  "#### Frogman\nLike I said Pops, your grandma's grandma—I've seen it all. Here's a little green serum from a far away land. Neutralizes all the pop.",
  "#### Princess Pops\nAll right already! Hands off. But, thank you. I have to go. My father is shopping me around to a local prince tonight.",
  "#### Frogman\nPrince Juicifer I hear. Lucky you indeed.",
  "#### Princess Pops\nHa! Actually I'm sick to my stomach, thinking of his fat fingers digging for food while he licks his lips at me. My last suitor kept wiping his greasy fingers on his lap, rubbing the erection under his napkin like I didn't notice, then plunging his hands back into the fondue for an excuse to rub more on himself. Meanwhile, I sat there and smiled at his parents. I'm a thousand years old, and they treat me like a doll. But do you know what I do to these princes, after our dads leave us to flirt by ourselves? After I've behaved for an hour, without touching my food?",
  "#### Frogman\nMake fun of their eating habits some more?",
  "#### Princess Pops\n_(licks her lips)_\nI eat them. Whole.",
  "## Act 2\n_6:00am. Frogman is in the kitchen slicing some breads._",
  "#### Frogman\nIs this... a complaint?\n\n_To the castle staff,\nI've never had a more horrendous meal in my life. I wouldn't call it curry, and I wouldn't call it casserole. It was a soupy abomination that I already feel gurgling its way back up. I demand you fire the kitchen staff at once if my son is ever to marry into this family. He is alone with Priness Pop now, but he'll be hearing about this from me.\nYours,\nKing Juicifer_\n\nOh brother. Another complaint about my casserole. Wasn't supposed to happen again. Fuuuu-",
  "#### Princess Pops\nYou found that jerkwad's letter?",
  "#### Frogman\nShiggity Princess, yeah. I gotta start looking for a new job.",
  "#### Princess Pops\nI took care of you Frogman. No one's going to see that letter, or hear from King Juicifer again.",
  "#### Frogman\nWhat! Ha. How'd he taste?",
  "#### Princess Pops\nNot good, but it was a favor to you. Today I'm very bloated as a result.",
  "#### Frogman\nSomething tells me I shouldn't be hanging around with you.",
  "#### Princess Pops\nNo? I'm pretty fun when I like you. Anyway, you kept your job. You're stuck here a little longer.",
  "#### Frogman\nSo, you're not interested in impressing these princes, huh?",
  "#### Princess Pops\nRoyal marriages suck. My dad was an out-of-towner when he met my mom. They got together, she became queen, fulfilled her destiny, all that. But she constantly has to play the part and follow his expectations. Me, no. You can catch me on the battlefield, having beers with friends, or belting out on stage with my band. But I won't be caught dead in a man's bed pretending I'm all cold, like I need a warm sweaty ass to feel safe.",
  "#### Frogman\nOh, man, I love a sweaty ass.",
  "#### Princess Pops\nA big hairy one?",
  "#### Frogman\nWith acne, yum.",
  "#### Princess Pops\nWhat about you Frogman?",
  "#### Frogman\nNever was married, never thought about it. I'm a working guy. Not much into family, you know?",
  "#### Princess Pops\nWhat about back in the sewer?",
  "#### Frogman\nSigh, yeah. It seems like so long ago. I have friends back there. Not sure we'd get along today. They're doing band stuff, hanging around the same dives, eating poop. I'm over it, I'm up here. So yeah, I'm basically on my own. I'm figuring things out.",
  "#### Princess Pops\nA loner. So sexy.",
  "#### Frogman\nI thought you might be into that.",
  "#### Princess Pops\n_(Licks her lips)_\nOh Frogman.",
  "#### Frogman\nYou gonna eat me?\n_(kisses Pops)_",
  "## Act 3\n_3 years later. Princess Pops puts her jewels on, getting ready for a royal banquet. She is impatient and having a fit._",
  "#### Frogman\nPops! Check this on out!",
  "#### Princess Pops\nSigh, Frog, I'm busy.",
  "#### Frogman\nDude I'm marching all around your bedroom. I'm like a 1980's Russian guy!",
  "#### Princess Pops\nWe have to go. Get ready!",
  "#### Frogman\nI'm ready.",
  "#### Princess Pops\nI can't believe you're wearing a t-shirt. I thought you wanted to be a part of my family.",
  "#### Frogman\nI'm not comfortable in royal suits.",
  "#### Princess Pops\nBecause you've never worn one!",
  "#### Frogman\nToday isn't even a big deal. I'll wear one when I need to.",
  "#### Princess Pops\nRight, and you'll look completely uncomfortable.",
  "#### Frogman\nYou're telling me I don't know how to wear a suit?",
  "#### Princess Pops\nThat's not what I said. It just looks better...",
  "#### Frogman\n...Better on someone more royal? Someone born in a castle?",
  "#### Princess Pops\nStop! I'm not trying to insult you. I'm just asking you to care.",
  "#### Frogman\nYou're asking me to be something I'm not. You're always holding out for me to change. When are you going to understand, you get what you get? Sorry I'm not someone else.",
  "#### Princess Pops\nIt's called compromise. Try it out.",
  "#### Frogman\nI compromise! Jesus!\n_(turns away)_",
  "#### Princess Pops\nI don't know what to say.",
  "#### Frogman\nJust go do your thing. I don't belong there.",
  "#### Princess Pops\nLook at me. God dammit, look at me!",
  "#### Frogman\nSorry I'm not perfect. Leave me alone.",
  "#### Princess Pops\n_(to self)\nI can't stand to see him like this. What did I do? Asked him for a favor. I bend and break for him every day. I show him love, and it's easy, most of the time. Is it this hard for other couples? Do other people have to march around the castle just to make their boyfriends happy? Or does Frogman just not love me enough?\n(to Frogman)_\nDo you not love me?",
  "#### Frogman\nI love you. But I'm not a prince...",
  "#### Princess Pops\nI don't want you to be a prince. I just want to be together.",
  "#### Frogman\nReally?",
  "#### Princess Pops\nYes...",
  "#### Frogman\nI'm such an idiot.",
  "#### Princess Pops\nNo, you're my prince, Frogman, no matter what..",
  "#### Frogman\nBaby I love you.",
  "#### Princess Pops\nI don't care about kingdom etiquette or what my dad says. We'll go away together if we have to.",
  "#### Frogman\nOkay.",
  "#### Princess Pops\nWha?",
  "#### Frogman\nWe've been in love for 37 months. We got rashes on our butts, moved across the country, wrote hundreds of angry journal pages, went through three road trips and 43 coffee shops. Everywhere we go, you warm my heart in the weirdest ways: crying on a therapist's couch, drinking wine in the cemetery, kissing in a steamy botanical garden, and laughing in the closet. It isn't the castle keeping us together... Sometimes, I can't believe it took thousands of years to find true love: we both gotta lotta jup and everybody thinks we're cute. But it turns out I'm the kind of guy who has a panic attack when I think about marriage. You remember when you wanted to break up while I was in Mexico?",
  "#### Princess Pops\nYeah.",
  "#### Frogman\nWe're kinda picky or cynical about true love. We're definitely haters. But I'm glad it wasn't easy, because we waited for each other, and I only want to love you. You're ma petite poule, my sweet bean, and a cute little ant. You feel so right, in so many ways, it's obvious we can stay together and be so happy, and I just want to. Let's stay together forever in the sewer, through panic attacks, caffeine withdrawal, and sobbing therapy sessions... Will you marry me?",
  "## Epilogue\n_10 years later. The sun is out at sea, casting orange shadows on a windswept beach. Princess Pops marches in place. Frogman marches too._",
  "#### Princess Pops\nBouncin around!",
  "#### Frogman\nBoun-bouncin around, bouncin!",
  "#### Princess Pops\nMmm, I love you Frog.",
  "#### Frogman\nI love you Pops.",
]
